# Site settings
title: Josh Fermin
header-img: img/image-1.png
email: joshfermin@gmail.com
description: "Welcome to my site!!"
baseurl: ""
url: "http://joshfermin.me"
twitter_username: jferms
github_username:  joshfermin

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

google_analytics: "UA-69109601-1"
